builds:
  - skip: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs'
    - '^test'
    - '^chore'
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  footer: |
    {{- if .repository }}
    **Full Changelog**: {{ .repository }}/compare/{{ .PreviousTag }}...{{ .Tag }}
    {{- end }}

    ---

    _Released with [GoReleaser Pro](https://goreleaser.com/pro)!_

# announce:
#   skip: "{{gt .Patch 0}}"
#   twitter:
#     enabled: true
#     message_template: '{{ .ProjectName }} {{ .Tag }} was just released! Get it now: {{ .ReleaseURL }}'

# variables:
#   repository: ""
