name: build

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  build:
    uses: cristalhq/.github/.github/workflows/build.yml@53335fadafd4a2409b342643789aea60465dbf40 # latest on main

  codeql:
    if: github.event.repository.public
    permissions:
      security-events: write
    uses: cristalhq/.github/.github/workflows/codeql.yml@53335fadafd4a2409b342643789aea60465dbf40 # latest on main

  release:
    if: github.event_name == 'workflow_dispatch'
    uses: cristalhq/.github/.github/workflows/release.yml@53335fadafd4a2409b342643789aea60465dbf40 # latest on main
    permissions: 
      contents: write
    with:
      tag: ${{ github.event.input.tag }}
